language: objective-c  #1
osx_image: xcode11.3 #2
xcode_project: mZone Poker.xcodeproj #3
xcode_scheme: mZone Pocker #4
xcode_destination: platform=iOS Simulator,OS=13.2.2,name=iPhone 11 #5
before_install:
- bundle install
- bundle exec pod install --repo-update
